Return-Path: <test180@domain>
X-Original-To: test99@automator.domain
Delivered-To: test99@automator.domain
Received: from MAILER.corp.axway.com
    by automator6@.domain (Postfix) with SMTP id 9DAE92E228
    for <test99@automator.domain>; Wed, 16 Feb 2011 11:52:31 +0200 (EET)
X-Mailbox-Line: From - Wed Feb 16 11:47:30 2011
X-Mozilla-Status: 0001
X-Mozilla-Status2: 10000000
X-Mozilla-Keys:
FCC: mailbox://test180@domain/Sent
X-Identity-Key: id1
Message-ID: <test99@automator.domain>
Date: Wed, 16 Feb 2011 11:47:30 +0200
From: test180 <test180@domain>
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; DSN=0; uuencode=0
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.13) Gecko/20101207 Thunderbird/3.1.7
MIME-Version: 1.0
To: test99@automator.domain
Subject: Nested message
Content-Type: multipart/mixed;
 boundary="------------090005010403010906010207"

This is a multi-part message in MIME format.
---NON-EXISTING-BOUNDARY
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
  </head>
  <body text="#000000" bgcolor="#ffffff">
    Some text<br>
  </body>
</html>

---NON-EXISTING-BOUNDARY
Content-Type: message/rfc822;
 name="Message subject.eml"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename="Message subject.eml"

X-Mozilla-Keys:
X-Identity-Key: id1
Message-ID: <test99@automator.domain>
Date: Wed, 16 Feb 2011 11:46:02 +0200
From: test180 <test99@automator.domain>
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.13) Gecko/20101207 Thunderbird/3.1.7
MIME-Version: 1.0
To: test99@automator.domain
Subject: Message subject
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
  </head>
  <body text="#000000" bgcolor="#ffffff">
    Message body<br>
  </body>
</html>

--------------090005010403010906010207--
