From bgwnabc@concentric.com Tue Dec  2 21:45:55 2003
Received: from localhost [127.0.0.1] by bfg.reinhouse.freeserve.co.uk
	with SpamAssassin (2.60 1.212-2003-09-23-exp);
	Wed, 03 Dec 2003 11:55:42 +0000
From: "Camille Underwood" <bgwnabc@concentric.com>
To: tim@reinhouse.freeserve.co.uk
Subject: Fwd: Need Meds? We Got Them. No prescription needed rd jsmeaqssb imciy
Date: Tue, 02 Dec 03 21:45:55 GMT
Message-Id: <omnxkixcmc$3sw-4b-$h0axla3-$zo9@yy0fj7ztkxrb>
X-Spam-Flag: YES
X-Spam-Checker-Version: SpamAssassin 2.60 (1.212-2003-09-23-exp) on 
	bfg.reinhouse.freeserve.co.uk
X-Spam-Level: *************
X-Spam-Status: Yes, hits=13.5 required=4.0 tests=BAYES_99,BIZ_TLD,
	DATE_SPAMWARE_Y2K,HTML_MESSAGE,MIME_HTML_NO_CHARSET,MIME_HTML_ONLY,
	MIME_HTML_ONLY_MULTI,MISSING_MIMEOLE,MISSING_OUTLOOK_NAME 
	autolearn=no version=2.60
MIME-Version: 1.0
Content-Type: multipart/mixed;
  boundary="----------=_3FCDCF3E.63A1635B"
Status: R
X-Status: N
X-KMail-EncryptionState:  
X-KMail-SignatureState:  
X-KMail-MDN-Sent:  

This is a multi-part message in MIME format.

------------=_3FCDCF3E.63A1635B
Content-Type: text/plain
Content-Disposition: inline
Content-Transfer-Encoding: 8bit

Spam detection software, running on the system "bfg.reinhouse.freeserve.co.uk", has
identified this incoming email as possible spam.  The original message
has been attached to this so you can view it (if it isn't spam) or block
similar future email.  If you have any questions, see
the administrator of that system for details.

Content preview:  Save 40%-90% on Hundreds of Prescription Drugs We are
  your private source for FDA Approved prescription medications. Once we
  receive your orders and one of our 24x7 onboard US Physicians will
  approve of your order (99.99% orders approved). Orders approved by 2 pm
  EST will receive their medication next business day via FedEX! (where
  available) [...] 

Content analysis details:   (13.5 points, 4.0 required)

 pts rule name              description
---- ---------------------- --------------------------------------------------
 4.2 DATE_SPAMWARE_Y2K      Date header uses unusual Y2K formatting
 0.1 HTML_MESSAGE           BODY: HTML included in message
 5.4 BAYES_99               BODY: Bayesian spam probability is 99 to 100%
                            [score: 1.0000]
 0.3 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
 0.6 MIME_HTML_NO_CHARSET   RAW: Message text in HTML without charset
 0.1 BIZ_TLD                URI: Contains a URL in the BIZ top-level domain
 1.6 MISSING_MIMEOLE        Message has X-MSMail-Priority, but no X-MimeOLE
 1.1 MIME_HTML_ONLY_MULTI   Multipart message only has text/html MIME parts
 0.1 MISSING_OUTLOOK_NAME   Message looks like Outlook, but isn't

The original message was not completely plain text, and may be unsafe to
open with some email clients; in particular, it may contain a virus,
or confirm that your address can receive spam.  If you wish to view
it, it may be safer to save it to a file and open it with an editor.


------------=_3FCDCF3E.63A1635B
Content-Type: message/rfc822; x-spam-type=original
Content-Description: original message before SpamAssassin
Content-Disposition: inline
Content-Transfer-Encoding: 8bit

Return-path: <bgwnabc@concentric.com>
Envelope-to: tim@localhost
Delivery-date: Wed, 03 Dec 2003 11:55:29 +0000
Received: from localhost ([127.0.0.1])
	by bfg.reinhouse.freeserve.co.uk with esmtp (Exim 4.24)
	id 1ARVbM-000436-Ne
	for tim@localhost; Wed, 03 Dec 2003 11:55:28 +0000
X-From_: bgwnabc@concentric.com Wed Dec 03 11:52:49 2003
Received: from pop.pol.net.uk [195.92.193.154]
	by localhost with POP3 (fetchmail-6.2.4)
	for tim@localhost (single-drop); Wed, 03 Dec 2003 11:55:28 +0000 (GMT)
Received: from [81.50.126.63] (helo=apastourelles-108-1-3-63.w81-50.abo.wanadoo.fr)
	by imailm5.svr.pol.co.uk with smtp (Exim 4.14)
	id 1ARVYl-0002As-RQ
	for tim@reinhouse.freeserve.co.uk; Wed, 03 Dec 2003 11:52:49 +0000
Received: from [143.85.47.205]
	by apastourelles-108-1-3-63.w81-50.abo.wanadoo.fr id <1184426-47423>;
	Tue, 02 Dec 2003 21:45:55 -0200
Message-ID: <omnxkixcmc$3sw-4b-$h0axla3-$zo9@yy0fj7ztkxrb>
From: "Camille Underwood" <bgwnabc@concentric.com>
Reply-To: "Camille Underwood" <bgwnabc@concentric.com>
To: tim@reinhouse.freeserve.co.uk
Subject: Fwd: Need Meds? We Got Them. No prescription needed rd jsmeaqssb imciy
Date: Tue, 02 Dec 03 21:45:55 GMT
X-Mailer: Atlas Mailer 2.0
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="B17__28C8..5_9AB0"
X-Priority: 5
X-MSMail-Priority: Low


--B17__28C8..5_9AB0
Content-Type: text/html;
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www=
w3.org/TR/html4/loose.dtd"><html><head><title>Save 40%-90% on Hundreds of=
 Prescription Drugs</title><style type=3D"text/css"><!-- .style5 {font-fam=
ily: Arial, Helvetica, sans-serif; font-size: 14px; } .style6 {font-size: =
10px} --></style></head><body><p class=3D"style5"> We are your private sou=
rce for FDA Approved prescription medications. Once we receive your orders=
 and one of our 24x7 onboard US Physicians will approve of your order (99.=
99% orders approved).<b> </b>Orders approved by <b>2 pm EST</b> will recei=
ve their medication <b>next business</b> day <b>via FedEX</b>! (where avai=
lable) </p><p align=3D"left" class=3D"style5">Vicodin, Phentermine, Viagra=
, Soma, Ambien, Floricet, Imitrex, Paxil, Prozac, Zoloft . . . and many ma=
ny more prescription drugs! </p><p class=3D"style5"><a href=3D"http://www.=
biz"><b>Start Saving. Order your Medications Here</b></a></p></body></htm=
l>sioiecijaskt
j u dywv   ki
et p  s ozvuwqk nelscfa q aidp mljlb  
v
mnrxmpa 
gbzfjp dif 

--B17__28C8..5_9AB0--




------------=_3FCDCF3E.63A1635B--


