Return-Path: <infos1.mercatoloterie@gmail.com>
Delivered-To: bruceg@ezmlm.org
Received: (fqmail 7436 invoked from network); 09 Feb 2007 14:33:17 -0000
Received: from mx06.futurequest.net (mx06.futurequest.net [69.5.6.177])
  by pt04.futurequest.net ([69.5.6.183])
  with FQDP via TCP; 09 Feb 2007 14:33:17 -0000
Received: (qmail 20592 invoked from network); 9 Feb 2007 14:33:17 -0000
Received: from pt04.futurequest.net (pt04.futurequest.net [69.5.6.183])
  by mx06.futurequest.net ([69.5.6.177])
  with QMQP via TCP; 09 Feb 2007 14:33:17 -0000
Delivered-To: webmaster@ezmlm.org
Received: (fqmail 7430 invoked from network); 09 Feb 2007 14:33:17 -0000
Received: from mx07.futurequest.net (mx07.futurequest.net [69.5.6.178])
  by pt04.futurequest.net ([69.5.6.183])
  with FQDP via TCP; 09 Feb 2007 14:33:17 -0000
Received: (qmail 12806 invoked from network); 9 Feb 2007 14:33:17 -0000
Received: from qb-out-0506.google.com (qb-out-0506.google.com [72.14.204.233])
  by mx07.futurequest.net ([69.5.6.178])
  with ESMTP via TCP; 09 Feb 2007 14:33:17 -0000
Received: by qb-out-0506.google.com with SMTP id q12so193287qbq
        for <webmaster@ezmlm.org>; Fri, 09 Feb 2007 06:33:17 -0800 (PST)
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=gmail.com; s=beta;
        h=received:message-id:date:from:sender:subject:mime-version:content-type:x-google-sender-auth;
        b=ev9c/xgznxRP05FofYAoHZQgl9o9hK5DpK8f3ROcsMozBpu4ZexaVsQX5TrPw0UhoByMs/yz6EEysRtS50OUWygAIcAoLjh55kdWD1nsF9lCidCELTZbmPHwcQd1b4QJHBP4XY6yu0oplHeDdCiH+jRml/voC9+DKYmo0vlcdsI=
Received: by 10.65.100.14 with SMTP id c14mr15898238qbm.1171031596648;
        Fri, 09 Feb 2007 06:33:16 -0800 (PST)
Received: by 10.65.252.6 with HTTP; Fri, 9 Feb 2007 06:33:16 -0800 (PST)
Message-ID: <a207c75a0702090633u142151cbid9efb905f5d44d86@mail.gmail.com>
Date: Fri, 9 Feb 2007 14:33:16 +0000
From: "MERCATO LOTERIE" <christian-roland@mercato-loterie.net>
Sender: infos1.mercatoloterie@gmail.com
Subject: LOTERIE MONDIALE.
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_42653_14282171.1171031596578"
X-Google-Sender-Auth: 574280e6bc5bff65
Content-Length: 3317

------=_Part_42653_14282171.1171031596578
Content-Type: text/plain; charset=WINDOWS-1252
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

ATTN : Mr /Mlle/Mme

A l'occasion de la 11e =E9dition de la f=EAte de l'Internet organis=E9e par=
 le
minist=E8re des Nouvelles Technologies et de l'Informatiques  qui =E0 eu li=
eu du
08 au 13 Janvier 2007 dernier =E0 l'h=F4tel Ivoire (C=F4te d'ivoire).

A cet effet MICROSOFT AFRIQUE, la soci=E9t=E9 INNOVA.SI, la FONDATION BILL =
GATES
partenaires, et la MERCATO LOTERIE parrain de la manifestation ont pr=E9sen=
t=E9
le tout nouveau portail collaboratif: MERCATO LOTERIE SERVER 2007.

Pendant cette manifestation un tirage au sort a =E9t=E9 effectu=E9 par le m=
inistre
des Nouvelles Technologies et de l'Informatiques  pour r=E9compenser les
meilleurs internautes de l'ann=E9e 2006.

Vous avez =E9t=E9 tirer au sort =E0 cette occasion et vous avez =E9t=E9 d=
=E9sign=E9 pour
empocher la baguette somme de =80100,000.00 Euros . Nous vous prions donc d=
e
bien vouloir prendre contact avec nous =E0 cette m=EAme adresse email.

Veuillez agr=E9e l'expression de nos sentiments les plus distingu=E9s.

F=E9licitation!!!!!!!

LA DIRECTION
CHRISTIAN ROLAND.
TEL: +22-508-377-099

------=_Part_42653_14282171.1171031596578
Content-Type: text/html; charset=WINDOWS-1252
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nb=
sp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nb=
sp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nb=
sp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </=
p>
<p>ATTN : Mr /Mlle/Mme<br>&nbsp;<br>A l&#39;occasion de la 11e =E9dition de=
 la f=EAte de l'Internet organis=E9e par le minist=E8re des Nouvelles Techn=
ologies et de l'Informatiques&nbsp; qui =E0 eu lieu du 08 au 13 Janvier 200=
7 dernier =E0 l'h=F4tel Ivoire (C=F4te d&#39;ivoire).=20
<br>&nbsp;<br>A cet effet MICROSOFT AFRIQUE, la soci=E9t=E9 <a href=3D"http=
://INNOVA.SI">INNOVA.SI</a>, la FONDATION BILL GATES partenaires, et la MER=
CATO LOTERIE parrain de la manifestation ont pr=E9sent=E9 le tout nouveau p=
ortail collaboratif: MERCATO LOTERIE SERVER 2007.=20
<br>&nbsp;<br>Pendant cette manifestation un tirage au sort a =E9t=E9 effec=
tu=E9 par le ministre des Nouvelles Technologies et de l'Informatiques&nbsp=
; pour r=E9compenser les meilleurs internautes de l&#39;ann=E9e 2006. </p>
<p>Vous avez =E9t=E9 tirer au sort =E0 cette occasion et vous avez =E9t=E9 =
d=E9sign=E9 pour empocher la baguette somme de =80100,000.00 Euros . Nous v=
ous prions donc de bien vouloir prendre contact avec nous =E0 cette m=EAme =
adresse email.</p>

<p>Veuillez agr=E9e l'expression de nos sentiments les plus distingu=E9s. <=
/p>
<p>F=E9licitation!!!!!!!<br>&nbsp;<br>LA DIRECTION <br>CHRISTIAN ROLAND.<br=
>TEL: +22-508-377-099</p>

------=_Part_42653_14282171.1171031596578--