version: ~> 1.0
os: linux
dist: bionic
language: java
jdk:
    openjdk8
before_install:
  #- wget https://maven.oracle.com/com/oracle/jdbc/ojdbc7/12.1.0.1/ojdbc7-12.1.0.1.jar --user=$MAVEN_ORACLE_USERNAME --password=$MAVEN_ORACLE_PASSWORD
  #- wget https://maven.oracle.com/com/oracle/jdbc/ojdbc7/12.1.0.1/ojdbc7-12.1.0.1.pom --user=$MAVEN_ORACLE_USERNAME --password=$MAVEN_ORACLE_PASSWORD
  #- mvn install:install-file -Dfile=ojdbc7-12.1.0.1.jar -DgroupId=com.oracle.jdbc -DartifactId=ojdbc7 -Dversion=12.1.0.1 -Dpackaging=pom -DpomFile=ojdbc7-12.1.0.1.pom
  #- mvn install:install-file -Dfile=ojdbc7-12.1.0.1.jar -DgroupId=com.oracle.jdbc -DartifactId=ojdbc7 -Dversion=12.1.0.1 -Dpackaging=jar -DpomFile=ojdbc7-12.1.0.1.pom
  - rm ~/.m2/settings.xml
  - cp settings.xml ~/.m2
script:
  # for fast Travis builds w/o tests: mvn clean install deploy -DskipTests=true or -P fast
  - mvn clean deploy
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - ats.team@axway.com
    on_success: change
    on_failure: always
env:
   global:
      # sonatype username
      - secure: "GL6d+vhKrewzM7i3krljBoV7ZgPBr1EGqda/bFTr6VIrafHfat6MzgVJsCNCXFCt+RzkhFKgVyQjBiOSWkZWpjg8mLEG5a2nFYZCcMChW+ahbFTZa8gUlhrRJ7wT+MtTeFhaynd8vwVS7IQweB3YOAANrSJ5qlOtqk1iOXFZEKtCplkH0JuojEYGe3Jcl38R9K1VcT2oAZgpA0+KxW9w1rCpiMho78dvFiDnnaG7ppMTw80LTeSrv6Bz30jtsfoU87GE2d9s0Yti5eORLtxKSGBBHxJAOpsrOfdwhbf0fpyN/bjhtMMImWf/85jK+nrF+UZcX4Y+a8Bk2Zo2FpY58az92f9//uGhyxu4YSS39o+ECTdpQpBf2XMEdMtSgJtJo+P5ffknnYi1NQyQITrjt0W9qJuavmiLEt/Om52Vsky16vU3CG+gcwFbNOpE+uworifrhI3o4HFqmczkLMzX+EbzdBUnO46MQhijScsoqXUr2ajPqrJhdD4rNfnnYWwjUsyru0XJqzffjkM+nUY9cVxmfjqJdVjozHWDFyapIrFHrEYT/eCI5/cIEURl/K83Y/sLnp9q2ghQZ45twi2cRurvMtESFudomj8OnqwCfB0def07E0EiVUmVxPfLRRA+Ob0F7CtShtjAcIh+un6MvZH4HcSRKPBgvTRHlFr5U3M="
      # sonatype password
      - secure: "QyqhQZxpKiekxbBw88zlUQ3AgcGHyXMpGewgiyp7WrR0M6ofkodEK0FK4GnaoFz5YTbKfRJ7QQSYw96NCfcOfym6vxHdPda4AG3GqxKwDvGo514Gfn2GMSezhFNWqTFuKCVceBQ4VEDtPYVtDtY7IK0H2EkOp0jvaDVzuKBeMFOHgFbAEY91xDl3wwV/k/MFbze1ZZNxI3kC59fTqXe6rHydSsSs7vfQjGwbsaFuP/b7N/ngrwubGSCmVs+ON/6T64qv67EC9rJzAWZE9XN0DYGkcH2gKPD2ePidjcGNFICKk6Crwe6SynXkf1jCk/aYeglu+yJRqlCMXsv8trx6R+Z5VcHSV0+4Pcm2LAeMXtvH0E/hykEkYlyx9u+As84ynWufF1zRC/sTf4zcc496sG6FZTebtRJhdsRAWrJXt53vKZUxzC6yGivniNGVVW0y8MJiSYwAIl3Rp6X2TUUXtHZ2KK1LL1KfWPE3qmdIz8xHSVX5dmHDfk4m0FcBY/zZODBXUFLqxlhFn8A2XqH5fRtmGfKzLbC5HV9fUfO/CWCk9n+2lY2nPSEe1qj9EXTS4/qMM76XZxqVRHAipV4kz9t0gUweT9pi/+UesLj5SK22J5+iH9YKADLjloJbyrKvxYot5aeCagkz8hGGjIU/lkg7dWr4m2++LK2HPdaLBMg="
      # maven oracle username
      - secure: "H/YnEGeeKVCCZFOw4V5CehFt3NkXumIv2KovkMb8EaWpv5HoutwHFjlmA8IG2uzqyXbWRm7MIi+1xybKcZmo5iW4TV0AHdoTZZW4xSZftskoXof7cowdy00Hhnw/l0aPJLFFLjdnd+dSmrcyFw9TFDsK7JoagXM67WXiTb7u0PD8XJfl5jfmjktMDYTYAYnel5fuW33ZCLg7bQNESDN4jfrD1WpJENFa5svo4aCzjSiAH1pk/37Cfyysr00zD5+cK9kh4Sf3x95w6TXcd+D027pj1ReVZcAXVKepIswAwFCC41ggAh49J2qjwr1L+mzorsctu+xPVMqZDJstnox2lI+f0Z+6QtvC8Ci/Xr1TYk27ZcMxUfm1KcuVG8z9QpjfjC2gAd1W+v880gNo5MlhEv+pbBRw5oUOampLKSMsjNIZdwfc+8PaIXQdoTsRyWVDJdj9PYRxP2T93MJCCIGZDjCvQKZD+AJlc9h9DrusNkYOu4+wo46ZbnzD1EVKsSprShQfshabMsSHgCFv5Xy11ojgG/gTVdx1DWrWXH1gb4czWrG7l0zZNFPEVhAvtQpPgq4+NJrYvcOCvZH/6ruDZx1AzEi1A2UBKhFoXVsRKQAHOGk72yNX3kOFixMNq/kKqEeBL4crDpZl9/b+R7SYK13IbKHyhVwSNhtyOni2wac="
      # maven oracle password
      - secure: "Nwbpgyzu6Jo0HY0RIQcl4KujOdYByVqNy5JVEoK4wddBh+VcgPez8vX5tjwjSY+4yP/Eu44fCG4fpS2cK035cNTc2zA36jGiMCvDsH8sDFNTj2aovIbq6iiral1OZJdy17j4GP5aQg/J9rftSaf9yyGxwJxtSBHB3oXtdEEMq/5sNzKYTppD8gJaHtxn4i2oHtW8NpfYvhyO13LBdddCxEM5HNqjPfRArN8m6i4ncCx0fzgaf+BafFCwZJXgL1Bt42Zq0PK6umSksrKVI5S7FKwQc1KE3cebieuFGKlM8r1/y4lHDAP6jb8/8pXqmhTxqn2FJQsBv76GcggSIuB42Q6yzyyacF60N2LB6xgT6/knR1VvTGXr3hOUSDdDmf/b+9AgYfTghfhA7xFCSbXeB9uPJr/WOmuOZOV5n0KRRvNf+lIfniH7DcHra+ehV8eXRKpiV9r1jJ6+m78fk47ueYzxSjC5L+W/N6PEOAP5k9LejjIeWfJ0ROwr2qKl+pC1mCyFrqXRm+2OliUypF5eTuBBOjphEu2L+8lAoANWRB3v5Gh8XKQVFmdosTzWAat6yRjjEAV9pDKFOylER8V+BN9oyIzMuqT+Qhy6dubn2L/agVm4rnutA85J36pZIly3BcKXX8Y6tcqe2Zp9WEtLl7ZAIxbAwuG5ok9/RW2Jepw="
