language: java
jdk:
    oraclejdk8
install: mvn clean install deploy --settings="settings.xml"
script: 
- mvn verify --settings="settings.xml"
notifications:
  email:
    recipients:
      - group.ats.team@axway.com
    on_success: change
    on_failure: always
env:
   global:
      - secure: "Bf+f7kwvBmLpPyRTL4tuXfIWbIf1juXo5i7x9fZ/n87VP3qyf1IfgCQW1MeP6ML/eegCx27jObanq9S4/hL6skvzPQVGzURTZ3JGNU5kDjvIqT9TSnLpP0JEiILlrFVKERicQRlft6XlMU20I1JsKKJYGn0LyEvZ9J8mzZDkiRmutm4cdV2uPc1Scn8xLPe3Z6zUZMSSK1u7hPcJUB21tpHilhXoVV8tmlZzMkEPwJ8D0UteETPO37hL48NeF7mF8ZUcbXIOmxdj3agPF1Z8wRotivNiRa8q2T6w32qOp+bEBAfjzaDXpPdWdj9mamGd5E5d+21Aw4HLnvYi6Q5HYBU/xQOnXiT4UwEZv2cu74haRJuXLV/D7CFgJ1WwQtlapRS1yUmHkH66JknG4rc5n3yWiivijbb9OLolzEIYurlmstR9rxx5tEK3ZVPJvTJ5kH28Zw5TlvgXKfdKZzf9qKB/jzkDcg+lanKSPqcW1yumLdBrxz89Bk72Lpn4ria6pj+/aVxoIbx3he3kmltqgTeel3PXQ25SyOf6fzMDGmwa45X7xXIJhUmJnWXkw5tqhkICrt6cxkmWMLWWJQxPQ5Zv333lol0Wr0C8dPp0hMWqukToAuLxTD3fIUWVVM7stXdnlstIwrCMLkZ0PTMstdhUj/jeBYcmiyadzykCVi4="
      - secure: "fuh2XyMLOPQNt27euOVTaf4eqnWZpY5F8Ce+EOBWC8cBH7jBOG7vzAGxvWk2XorE2XIc72qY2SduH9wOKJZVwzrcRf1qZpzjFjoyB4FV1MCplF3akBlA8jVzpx/HHe/2L2Zi8JRLgMsWKZFx/vweAwlvS9yJjSTNnlT/5T60stCOlJRF9hyZcrtpcwUxgtSZwSWJqqMBSe/Vb+OLG+Czf98NMjw2sUPzHc/RVZvdQhtkV+3oK20OZbR6keEpwfTuAZR/8Szgpwnm6iVSW4EDZOP2mdWrpAbRZW7WakaPGD/ZFaIdsd6REyUJHbtQEt02tSrnlI0azoTvHFYGy2h7w6mMB1O5wjJz7gOnj1dAOsGvuCUsp0hlV4zhlkZEnuprA0w1tvgGu3BZuM12LYzKNpBBOsIIDTzdmFF3UYDnq1XlVAvpJu0OYcg3Xd/DrMH89uwcn9a5gvRkneLjEUfPXHfnMpDM852b5nsAXeyQ/iec7u+TYqjLRpPGVq6Hl40Pb3Q5BFUNzpWOBl5eR0NL/mP3HGfAXMvJbCtkBjC2KcXNZFCl+pqfrCrS5MDxMGmaMj+ow948b/SpH6vuQ9eZ9HYjy+CiaXrAjBqQrSo4zbwTTYY5AMLU5whG8yGnplvOTXPB8fxomn2U00n/jT499HAb3PDWJtYgS+QBdAnskx0="
