language: java
jdk:
    oraclejdk8
install: mvn clean install deploy --settings="settings.xml"
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - group.ats.team@axway.com
    on_success: change
    on_failure: always
env:
   global:
      - secure: "GL6d+vhKrewzM7i3krljBoV7ZgPBr1EGqda/bFTr6VIrafHfat6MzgVJsCNCXFCt+RzkhFKgVyQjBiOSWkZWpjg8mLEG5a2nFYZCcMChW+ahbFTZa8gUlhrRJ7wT+MtTeFhaynd8vwVS7IQweB3YOAANrSJ5qlOtqk1iOXFZEKtCplkH0JuojEYGe3Jcl38R9K1VcT2oAZgpA0+KxW9w1rCpiMho78dvFiDnnaG7ppMTw80LTeSrv6Bz30jtsfoU87GE2d9s0Yti5eORLtxKSGBBHxJAOpsrOfdwhbf0fpyN/bjhtMMImWf/85jK+nrF+UZcX4Y+a8Bk2Zo2FpY58az92f9//uGhyxu4YSS39o+ECTdpQpBf2XMEdMtSgJtJo+P5ffknnYi1NQyQITrjt0W9qJuavmiLEt/Om52Vsky16vU3CG+gcwFbNOpE+uworifrhI3o4HFqmczkLMzX+EbzdBUnO46MQhijScsoqXUr2ajPqrJhdD4rNfnnYWwjUsyru0XJqzffjkM+nUY9cVxmfjqJdVjozHWDFyapIrFHrEYT/eCI5/cIEURl/K83Y/sLnp9q2ghQZ45twi2cRurvMtESFudomj8OnqwCfB0def07E0EiVUmVxPfLRRA+Ob0F7CtShtjAcIh+un6MvZH4HcSRKPBgvTRHlFr5U3M="
      - secure: "QyqhQZxpKiekxbBw88zlUQ3AgcGHyXMpGewgiyp7WrR0M6ofkodEK0FK4GnaoFz5YTbKfRJ7QQSYw96NCfcOfym6vxHdPda4AG3GqxKwDvGo514Gfn2GMSezhFNWqTFuKCVceBQ4VEDtPYVtDtY7IK0H2EkOp0jvaDVzuKBeMFOHgFbAEY91xDl3wwV/k/MFbze1ZZNxI3kC59fTqXe6rHydSsSs7vfQjGwbsaFuP/b7N/ngrwubGSCmVs+ON/6T64qv67EC9rJzAWZE9XN0DYGkcH2gKPD2ePidjcGNFICKk6Crwe6SynXkf1jCk/aYeglu+yJRqlCMXsv8trx6R+Z5VcHSV0+4Pcm2LAeMXtvH0E/hykEkYlyx9u+As84ynWufF1zRC/sTf4zcc496sG6FZTebtRJhdsRAWrJXt53vKZUxzC6yGivniNGVVW0y8MJiSYwAIl3Rp6X2TUUXtHZ2KK1LL1KfWPE3qmdIz8xHSVX5dmHDfk4m0FcBY/zZODBXUFLqxlhFn8A2XqH5fRtmGfKzLbC5HV9fUfO/CWCk9n+2lY2nPSEe1qj9EXTS4/qMM76XZxqVRHAipV4kz9t0gUweT9pi/+UesLj5SK22J5+iH9YKADLjloJbyrKvxYot5aeCagkz8hGGjIU/lkg7dWr4m2++LK2HPdaLBMg="
      - secure: "BfAVxdmhaaPaP7Dp2/oB7BmB7TBCCyw8MXPJj8wGEbHYBpUv8XaOWowf54mOUhk68cpC5K9F+goksdhC9Li+PYD11cNv6MBMiL1Z4/nM+WKWpTiwOhRtucU/UtStN8LM+/5tTSWVyPksNu1l7kTd0Gay0pMSaM0K44lyqKI2EYseOhoTqV9r0O/YjIsVW61Snu+7j3AzH+HoyGsNk6L1ncmUwCLqkKxYMAuRUmxkgEdTWdO7J0HqLHZXb3MUovzAVjbJyzsc852ZLFQ923hzeNm/bX/RL3kTQeoHgDlpoMyTOS0u2G46gAw8MpegeW6j20HjwcAxBnwfwRxeKN5ENiOxsgu53Q00gQA+zI9W5fSVUbGrJDxWuxa0wMxuWHO9k7hPujgR+GWbUBVHj+lPriIBK6OMz4nezDw1Uh0RiLGszWmr3UP8JlZuGaUN4jBsb6u1VwzeGIF5AYPUiHB+uKHcCI4KDFCSV/NXNOG3n/c9mG7fvKc20udJASBkhbJh4jA/r4HhBIwciOFHBwwhIo0Hw7PGjc5a8nF4atDI2to73hnFAshGFjIMwHkrywWimZqOgXhxuvE7RIlIsZZnA1lOtq1l5akq+wlLJ6ZJBxtBL2QADP4IU+8XfM27POuAbLfn6+YmiCIr7x04YvuUClBPI21XNmOhSD4a9BPlOaM="
      

